MovieApp/config/routes.rb
Rails.application.routes.draw do

  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie
  get '/actors' => 'actors#index'
  get '/actors/:id' => 'actors#show', as: :actor

end

MovieApp/app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :parts
  has_many :movies, through: :parts
end

MovieApp/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :parts
  has_many :actors, through: :parts
end

MovieApp/app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

MovieApp/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
    @filmography = @actor.movies
  end

end

MovieApp/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
end

MovieApp/app/helpers/actors_helper.rb
module ActorsHelper
end

MovieApp/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieApp/app/views/actors/index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row cf">

         <% @actors.each do |a| %>
          <div class="actor col-xs-2">
            <%= image_tag a.image %>
            <h3><%= a.first_name %> <%= a.last_name %></h3>
            <%= link_to "Learn more", actor_path(a.id) %>
            <p><%= a.bio %></p>
          </div>
          <% end %>
      </div>

        <div class="moviesList col-xs-2">
          <h2><%= link_to "Jump to Movies List", "/movies" %></h2>
        </div>


</div>

MovieApp/app/views/actors/show.html.erb
<div class="main actor-show">
    <div class="container">

    <!-- Display an actor's info here -->
    <div class="actor">
      <%= image_tag @actor.image %>
      <div class="info">
        <h3 class="actor-name"><%= @actor.first_name %> <%= @actor.last_name %></h3>
        <p class="actor-bio"><%= @actor.bio %></p>
      </div>
    </div>

    <h2>Movies</h2>
    <!-- Display each movie's info here -->
    <% @filmography.each do |f| %>
    <div class="movie">
      <%= image_tag f.image %>
      <h3 class="movie-title"><%= f.title %></h3>
      <%= link_to "Learn more", movie_path(f.id) %>
      <p class="movie-release-year"><%= f.release_year %></p>
      <p class="movie-plot"><%= f.plot %></p>
    </div>
    <% end %>

  </div>
</div>

MovieApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolt Movie Database</title>
    <link href='http://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo.svg" height="40">
        <h1>Bolt Movie Database</h1>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

MovieApp/app/views/movies/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
  <h2>Popular Films</h2>

    <% @movies.each do |m| %>
      <div class="movie">
        <%= image_tag m.image%>
        <h3><%= m.title %></h3>
        <p><%= m.release_year %></p>
        <p><%= m.plot %></p>
        <%= link_to "Learn more", movie_path(m.id) %>
      </div>
    <% end %>

  <div class="actorsList">
    <h2><%= link_to "Jump to Actors List", "/actors" %></h2>
  </div>

  </div>
</div>

MovieApp/app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">

      <!-- Display the movie's info here -->
      <div class="info">
        <%= image_tag @movie.image%>
        <h3 class="movie-title"><%= @movie.title %></h3>
        <p class="movie-release-year"><%= @movie.release_year %></p>
        <p class="movie-plot"><%= @movie.plot  %></p>
      </div>
    </div>

    <h2>Cast</h2>
    <% @actors.each do |a| %>
    <div class="actor">
      <%= image_tag a.image %>
      <h3 class="actor-name"><%= a.first_name %> <%= a.last_name %></h3>
      <%= link_to "Learn more", actor_path(a.id) %>
      <p class="actor-bio"><%= a.bio %></p>
    </div>
    <% end %>

  </div>
</div>